We_Box:

<We_Box>:
    padding:"10px"
    orientation:"vertical"
    We_Grid:
    Button:
        text:"Box"
    Button:
        text:"Box1"
    Label:
        text:"We Improvements"
<We_Grid>:
    cols:3
    rows:2
    Button:
        text:"We"
    Button:
        text:"We1"
    Button:
        text:"We2"
    Button:
        text:"We3"
    Button:
        text:"We4"
    Label:
        text:"We Improvements"